import { defineConfig } from "tsup"

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/primitives/*.tsx",
    "src/primitives/*.ts",
    "src/forms/*.tsx",
    "src/forms/*.ts",
    "src/overlays/*.tsx",
    "src/overlays/*.ts",
    "src/navigation/*.tsx",
    "src/navigation/*.ts",
    "src/data/*.tsx",
    "src/data/*.ts",
    "src/domain/*.tsx",
    "src/domain/*.ts",
    "src/hooks/*.ts",
    "src/lib/*.ts",
    "!src/**/_internal/**",
    "!src/**/_*.ts",
    "!src/**/_*.tsx",
    "!src/**/*.stories.*",
    "!src/**/*.test.*",
  ],
  format: ["esm"],
  dts: { compilerOptions: { jsx: "react-jsx" } },
  sourcemap: false,
  clean: true,
  splitting: true,
  treeshake: true,
  external: ["react", "react-dom"],
  tsconfig: "./tsconfig.build.json",
})
